title: My Portfolio
author: Sneha Elango
email: snehaelngovan04@gmail.com
description: A portfolio showcasing my work.
baseurl: "" # Remove any value here
url: "https://Snehaelg-portfolio.github.io" # Replace with your GitHub username
github_username: Snehaelg
linkedin_username: sneha-elango-0a11931a0
include:
  - _pages
  - _portfolio
